/**
 * Numerical validation against the NIST Statistical Reference Datasets (StRD).
 *
 * The rest of the suite checks that an analysis runs and returns plausible
 * numbers. This file checks that the numbers are *right*, against values
 * certified by NIST in extended precision — the standard yardstick for
 * statistical software. Two of the four datasets are deliberately hostile:
 *
 *   - Longley is the classic ill-conditioned regression (1967); naive normal
 *     equations lose most of their significant digits on it.
 *   - AtmWtAg carries seven constant leading digits (107.868…), so its
 *     between-group sum of squares is ~1e-9. A one-pass "sum of squares minus
 *     square of sums" variance collapses here.
 *
 * Tolerances are relative, not absolute: the certified quantities here span
 * 1e-9 (AtmWtAg sums of squares) to 1e8 (Longley regression sum of squares), and
 * an absolute bound would be vacuous at one end and impossible at the other.
 *
 * `expectNotFlattenedToZero` is kept as a separate guard. Returning exactly 0 for
 * a certified-nonzero quantity is what output rounding used to do (#12), and a
 * relative tolerance alone reports that as merely "100% off" rather than naming
 * the failure.
 *
 * Longley is marked `it.fails` against the issue that explains it, so the defect
 * stays executable evidence instead of being absorbed into a looser tolerance.
 *
 * Fixture: `e2e/fixtures/nist-strd.json`, regenerated by
 * `node scripts/fetch-nist-strd.mjs`.
 */

import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { InferentialStats } from '../src/index';
import {
  expectCloseTo as expectWithinTolerance,
  expectNotFlattenedToZero,
} from './support/numeric-assertions';
import fixtureFile from './fixtures/nist-strd.json';

const workerUrl = new URL('../dist/stats-worker.js', import.meta.url).href;

interface CertifiedParameter {
  index: number;
  estimate: number;
  standardError: number;
}

interface CertifiedAnovaRow {
  df: number;
  sumOfSquares: number;
  meanSquare: number | null;
  fStatistic: number | null;
}

interface RegressionFixture {
  source: string;
  procedure: 'linear-regression';
  columns: string[];
  rows: Record<string, number>[];
  certified: {
    parameters: CertifiedParameter[];
    rSquared: number;
    residualStandardDeviation: number;
    anova: Record<string, CertifiedAnovaRow>;
  };
}

interface AnovaFixture {
  source: string;
  procedure: 'anova-oneway';
  columns: string[];
  rows: Record<string, number>[];
  certified: {
    between: CertifiedAnovaRow;
    within: CertifiedAnovaRow;
    rSquared: number;
    residualStandardDeviation: number | null;
  };
}

const fixtures = fixtureFile.fixtures as unknown as Record<string, RegressionFixture | AnovaFixture>;

/**
 * Every tolerance in this file is relative — the certified values span 1e-9
 * (AtmWtAg sums of squares) to 1e8 (Longley regression sum of squares), and an
 * absolute bound would be meaningless at one end and vacuous at the other. The
 * shared helper accepts either kind, so this wrapper fixes the choice for the
 * whole file and keeps the call sites reading as a single number.
 */
const expectCloseTo = (actual: unknown, certified: number, tolerance: number, label: string): void =>
  expectWithinTolerance(actual, certified, { relative: tolerance }, label);

describe('NIST StRD certified values', () => {
  let stats: InferentialStats;

  beforeAll(async () => {
    stats = new InferentialStats({ workerUrl });
    await stats.init();
  });

  afterAll(() => {
    stats.destroy();
  });

  describe.each([
    // The well-conditioned baseline.
    ['Norris', 1e-9, null],
    // Longley is the classic ill-conditioned regression. It currently fails for
    // a reason that has nothing to do with conditioning: `linearRegression`
    // defaults to stepwise selection and fits a two-predictor model instead of
    // the six-predictor one that was asked for. See issue #13.
    ['Longley', 1e-9, '#13'],
  ] as const)('%s — linear regression', (name, TOLERANCE, knownDefect) => {
    const fixture = fixtures[name] as RegressionFixture;
    const predictors = fixture.columns.filter((column) => column !== 'y');

    const test = knownDefect ? it.fails : it;
    const title = knownDefect
      ? `does NOT match the certified regression statistics — known defect ${knownDefect}`
      : `matches the certified regression statistics within ${TOLERANCE.toExponential(0)} relative error`;

    test(title, async () => {
      const result = await stats.linearRegression({
        data: fixture.rows,
        dependentVariable: 'y',
        independentVariables: predictors,
      });
      expect(result.success, result.error).toBe(true);

      const { certified } = fixture;
      expect(result.data.observations).toBe(fixture.rows.length);
      expectCloseTo(result.data.rSquared, certified.rSquared, TOLERANCE, `${name} R-squared`);
      expectCloseTo(
        result.data.residualStdError,
        certified.residualStandardDeviation,
        TOLERANCE,
        `${name} residual standard deviation`,
      );

      // B0 is the intercept; B1..Bn follow the predictor order in the file.
      const intercept = result.data.coefficients.find(
        (coefficient) => !predictors.includes(coefficient.variable),
      );
      expect(intercept, `${name}: no intercept term in the output`).toBeDefined();

      certified.parameters.forEach((parameter) => {
        const coefficient =
          parameter.index === 0 ? intercept! : result.data.coefficients.find(
            (candidate) => candidate.variable === predictors[parameter.index - 1],
          );
        expect(coefficient, `${name}: B${parameter.index} missing from the output`).toBeDefined();
        expectCloseTo(coefficient!.coefficient, parameter.estimate, TOLERANCE, `${name} B${parameter.index}`);
        expectCloseTo(
          coefficient!.stdError,
          parameter.standardError,
          TOLERANCE,
          `${name} SE(B${parameter.index})`,
        );
      });

      const anovaRows = result.data.anova?.rows ?? [];
      Object.entries(certified.anova).forEach(([source, row]) => {
        const actual = anovaRows.find((candidate) => candidate.source.toLowerCase() === source);
        expect(actual, `${name}: ANOVA row "${source}" missing from the output`).toBeDefined();
        expect(actual!.df, `${name} ${source} df`).toBe(row.df);
        expectCloseTo(actual!.sumOfSquares, row.sumOfSquares, TOLERANCE, `${name} ${source} SS`);
        if (row.meanSquare !== null) {
          expectCloseTo(actual!.meanSquare, row.meanSquare, TOLERANCE, `${name} ${source} MS`);
        }
        if (row.fStatistic !== null) {
          expectCloseTo(actual!.fStatistic, row.fStatistic, TOLERANCE, `${name} ${source} F`);
        }
      });
    });
  });

  describe.each([
    ['SiRstv', 1e-9, null],
    // Seven constant leading digits (107.8681568…), so the certified
    // between-group sum of squares is 3.638341875e-9. Before #12 this came back
    // as exactly 0; it is now 3.638341886915592e-9, a relative error of 3.275e-9.
    // That residual is genuine catastrophic cancellation rather than a defect —
    // subtracting values that agree to seven digits spends seven of the sixteen
    // a double carries, which is exactly what NIST publishes this dataset to
    // expose. Tolerance is the measured error rounded up to the next power of ten.
    ['AtmWtAg', 1e-8, null],
  ] as const)('%s — one-way ANOVA', (name, TOLERANCE, knownDefect) => {
    const fixture = fixtures[name] as AnovaFixture;

    const test = knownDefect ? it.fails : it;
    const title = knownDefect
      ? `does NOT match the certified ANOVA table — known defect ${knownDefect}`
      : `matches the certified ANOVA table within ${TOLERANCE.toExponential(0)} relative error`;

    test(title, async () => {
      const result = await stats.anovaOneway({
        data: fixture.rows,
        variable: 'y',
        groupVariable: 'instrument',
      });
      expect(result.success, result.error).toBe(true);

      const { certified } = fixture;
      expect(result.data.degreesOfFreedomBetween).toBe(certified.between.df);
      expect(result.data.degreesOfFreedomWithin).toBe(certified.within.df);

      expectNotFlattenedToZero(result.data.sumOfSquaresBetween, certified.between.sumOfSquares, `${name} SS between`);
      expectNotFlattenedToZero(result.data.meanSquareBetween, certified.between.meanSquare!, `${name} MS between`);
      expectCloseTo(result.data.sumOfSquaresBetween, certified.between.sumOfSquares, TOLERANCE, `${name} SS between`);
      expectCloseTo(result.data.sumOfSquaresWithin, certified.within.sumOfSquares, TOLERANCE, `${name} SS within`);
      expectCloseTo(result.data.meanSquareBetween, certified.between.meanSquare!, TOLERANCE, `${name} MS between`);
      expectCloseTo(result.data.meanSquareWithin, certified.within.meanSquare!, TOLERANCE, `${name} MS within`);
      expectCloseTo(result.data.fStatistic, certified.between.fStatistic!, TOLERANCE, `${name} F`);

      // For a one-way ANOVA the certified R-squared is SS_between / SS_total,
      // which is what eta squared reports.
      expectCloseTo(result.data.etaSquared, certified.rSquared, TOLERANCE, `${name} eta squared`);
    });
  });
});
