/**
 * Numerical validation against the NIST Statistical Reference Datasets (StRD).
 *
 * The rest of the suite checks that an analysis runs and returns plausible
 * numbers. This file checks that the numbers are *right*, against values
 * certified by NIST in extended precision — the standard yardstick for
 * statistical software. Two of the four datasets are deliberately hostile:
 *
 *   - Longley is the classic ill-conditioned regression (1967); naive normal
 *     equations lose most of their significant digits on it.
 *   - AtmWtAg carries seven constant leading digits (107.868…), so its
 *     between-group sum of squares is ~1e-9. A one-pass "sum of squares minus
 *     square of sums" variance collapses here.
 *
 * How the bounds are shaped, and why it is not one number:
 *
 * The Python layer rounds every statistic to six *decimal places* before
 * returning it (issue #12). That is an absolute truncation, so the relative
 * accuracy it leaves behind depends entirely on the magnitude of the value —
 * Norris SE(B1) = 4.298e-4 keeps three digits, and AtmWtAg's 3.638e-9 sum of
 * squares keeps none at all. Chasing a single relative tolerance therefore just
 * surfaces whichever certified quantity happens to be smallest.
 *
 * So each assertion passes if *either* bound holds: the relative bound that
 * double precision should actually achieve, or the absolute resolution of
 * `round(x, 6)`. Today almost everything passes only by the absolute clause.
 * When #12 is fixed, drop `absolute` and the relative bound becomes the real
 * guarantee.
 *
 * An absolute bound cannot see the worst consequence of the rounding, though: a
 * certified-nonzero quantity coming back as exactly 0 is within 5e-7 of the truth
 * and still useless. That case is asserted separately, and AtmWtAg is marked
 * `it.fails` against it — so the defect stays executable evidence rather than
 * being absorbed into a looser tolerance.
 *
 * Fixture: `e2e/fixtures/nist-strd.json`, regenerated by
 * `node scripts/fetch-nist-strd.mjs`.
 */

import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { InferentialStats } from '../src/index';
import fixtureFile from './fixtures/nist-strd.json';

const workerUrl = new URL('../dist/stats-worker.js', import.meta.url).href;

interface CertifiedParameter {
  index: number;
  estimate: number;
  standardError: number;
}

interface CertifiedAnovaRow {
  df: number;
  sumOfSquares: number;
  meanSquare: number | null;
  fStatistic: number | null;
}

interface RegressionFixture {
  source: string;
  procedure: 'linear-regression';
  columns: string[];
  rows: Record<string, number>[];
  certified: {
    parameters: CertifiedParameter[];
    rSquared: number;
    residualStandardDeviation: number;
    anova: Record<string, CertifiedAnovaRow>;
  };
}

interface AnovaFixture {
  source: string;
  procedure: 'anova-oneway';
  columns: string[];
  rows: Record<string, number>[];
  certified: {
    between: CertifiedAnovaRow;
    within: CertifiedAnovaRow;
    rSquared: number;
    residualStandardDeviation: number | null;
  };
}

const fixtures = fixtureFile.fixtures as unknown as Record<string, RegressionFixture | AnovaFixture>;

/**
 * Relative error, because the certified values span 1e-9 (AtmWtAg sums of
 * squares) to 1e8 (Longley regression sum of squares). An absolute tolerance
 * would be meaningless at one end and vacuous at the other.
 */
const relativeError = (actual: number, certified: number): number =>
  certified === 0 ? Math.abs(actual) : Math.abs((actual - certified) / certified);

interface Bounds {
  /** What double precision should achieve once issue #12 is fixed. */
  relative: number;
  /** The resolution of `round(x, 6)`. Remove this once #12 is fixed. */
  absolute: number;
}

function expectCloseTo(actual: unknown, certified: number, bounds: Bounds, label: string): void {
  expect(typeof actual, `${label} should be a number`).toBe('number');
  const relative = relativeError(actual as number, certified);
  const absolute = Math.abs((actual as number) - certified);
  expect(
    relative <= bounds.relative || absolute <= bounds.absolute,
    `${label}: got ${actual}, certified ${certified} — relative error ` +
      `${relative.toExponential(3)} (bound ${bounds.relative.toExponential(0)}), ` +
      `absolute error ${absolute.toExponential(3)} (bound ${bounds.absolute.toExponential(0)})`,
  ).toBe(true);
}

/**
 * `round(x, 6)` turns any certified value below 5e-7 into exactly 0, which no
 * absolute tolerance can catch. A sum of squares that NIST certifies as nonzero
 * must not come back as zero.
 */
function expectNotFlattenedToZero(actual: unknown, certified: number, label: string): void {
  if (certified === 0) return;
  expect(actual, `${label}: certified ${certified} but the library returned exactly 0`).not.toBe(0);
}

/** Bounds shared by every dataset; see the file comment for why there are two. */
const BOUNDS: Bounds = { relative: 1e-9, absolute: 5e-7 };

describe('NIST StRD certified values', () => {
  let stats: InferentialStats;

  beforeAll(async () => {
    stats = new InferentialStats({ workerUrl });
    await stats.init();
  });

  afterAll(() => {
    stats.destroy();
  });

  describe.each([
    // The well-conditioned baseline. Passes today only via the absolute bound:
    // its worst relative error is 4.727e-4, on SE(B1) = 4.29796848199937e-4.
    ['Norris', null],
    // Longley is the classic ill-conditioned regression. It currently fails for
    // a reason that has nothing to do with conditioning: `linearRegression`
    // defaults to stepwise selection and fits a two-predictor model instead of
    // the six-predictor one that was asked for. See issue #13.
    ['Longley', '#13'],
  ] as const)('%s — linear regression', (name, knownDefect) => {
    const fixture = fixtures[name] as RegressionFixture;
    const predictors = fixture.columns.filter((column) => column !== 'y');

    const test = knownDefect ? it.fails : it;
    const title = knownDefect
      ? `does NOT match the certified regression statistics — known defect ${knownDefect}`
      : 'matches the certified regression statistics';

    test(title, async () => {
      const result = await stats.linearRegression({
        data: fixture.rows,
        dependentVariable: 'y',
        independentVariables: predictors,
      });
      expect(result.success, result.error).toBe(true);

      const { certified } = fixture;
      expect(result.data.observations).toBe(fixture.rows.length);
      expectCloseTo(result.data.rSquared, certified.rSquared, BOUNDS, `${name} R-squared`);
      expectCloseTo(
        result.data.residualStdError,
        certified.residualStandardDeviation,
        BOUNDS,
        `${name} residual standard deviation`,
      );

      // B0 is the intercept; B1..Bn follow the predictor order in the file.
      const intercept = result.data.coefficients.find(
        (coefficient) => !predictors.includes(coefficient.variable),
      );
      expect(intercept, `${name}: no intercept term in the output`).toBeDefined();

      certified.parameters.forEach((parameter) => {
        const coefficient =
          parameter.index === 0 ? intercept! : result.data.coefficients.find(
            (candidate) => candidate.variable === predictors[parameter.index - 1],
          );
        expect(coefficient, `${name}: B${parameter.index} missing from the output`).toBeDefined();
        expectCloseTo(coefficient!.coefficient, parameter.estimate, BOUNDS, `${name} B${parameter.index}`);
        expectCloseTo(
          coefficient!.stdError,
          parameter.standardError,
          BOUNDS,
          `${name} SE(B${parameter.index})`,
        );
      });

      const anovaRows = result.data.anova?.rows ?? [];
      Object.entries(certified.anova).forEach(([source, row]) => {
        const actual = anovaRows.find((candidate) => candidate.source.toLowerCase() === source);
        expect(actual, `${name}: ANOVA row "${source}" missing from the output`).toBeDefined();
        expect(actual!.df, `${name} ${source} df`).toBe(row.df);
        expectCloseTo(actual!.sumOfSquares, row.sumOfSquares, BOUNDS, `${name} ${source} SS`);
        if (row.meanSquare !== null) {
          expectCloseTo(actual!.meanSquare, row.meanSquare, BOUNDS, `${name} ${source} MS`);
        }
        if (row.fStatistic !== null) {
          expectCloseTo(actual!.fStatistic, row.fStatistic, BOUNDS, `${name} ${source} F`);
        }
      });
    });
  });

  describe.each([
    // Worst relative error 3.399e-5, on MS between = 0.0127865654.
    ['SiRstv', null],
    // Seven constant leading digits, so the certified between-group sum of
    // squares is 3.6e-9 — smaller than the resolution of `round(x, 6)`, which
    // returns exactly 0 for it. See issue #12.
    ['AtmWtAg', '#12'],
  ] as const)('%s — one-way ANOVA', (name, knownDefect) => {
    const fixture = fixtures[name] as AnovaFixture;

    const test = knownDefect ? it.fails : it;
    const title = knownDefect
      ? `does NOT match the certified ANOVA table — known defect ${knownDefect}`
      : 'matches the certified ANOVA table';

    test(title, async () => {
      const result = await stats.anovaOneway({
        data: fixture.rows,
        variable: 'y',
        groupVariable: 'instrument',
      });
      expect(result.success, result.error).toBe(true);

      const { certified } = fixture;
      expect(result.data.degreesOfFreedomBetween).toBe(certified.between.df);
      expect(result.data.degreesOfFreedomWithin).toBe(certified.within.df);

      expectNotFlattenedToZero(result.data.sumOfSquaresBetween, certified.between.sumOfSquares, `${name} SS between`);
      expectNotFlattenedToZero(result.data.meanSquareBetween, certified.between.meanSquare!, `${name} MS between`);
      expectCloseTo(result.data.sumOfSquaresBetween, certified.between.sumOfSquares, BOUNDS, `${name} SS between`);
      expectCloseTo(result.data.sumOfSquaresWithin, certified.within.sumOfSquares, BOUNDS, `${name} SS within`);
      expectCloseTo(result.data.meanSquareBetween, certified.between.meanSquare!, BOUNDS, `${name} MS between`);
      expectCloseTo(result.data.meanSquareWithin, certified.within.meanSquare!, BOUNDS, `${name} MS within`);
      expectCloseTo(result.data.fStatistic, certified.between.fStatistic!, BOUNDS, `${name} F`);

      // For a one-way ANOVA the certified R-squared is SS_between / SS_total,
      // which is what eta squared reports.
      expectCloseTo(result.data.etaSquared, certified.rSquared, BOUNDS, `${name} eta squared`);
    });
  });
});
